### PR TITLE
Add urecover and urecoverWith

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by igrep** [comment]
@sol Thank you! But can you tell me the detailed background? What is the use case?

**Comment by sol** [comment]
https://github.com/hspec/hspec/pull/573

That's my use case for now.

**Comment by igrep** [comment]
Released! https://hackage.haskell.org/package/unicode-show-0.1.1.0

**Comment by fumieval** [comment]
Nice. I was missing these functions too

**Comment by sol** [comment]
Thanks a lot!

**Pull request merged**
